#!/bin/bash

AWS_REGION=${AWS_REGION-"us-east-1"}
usage(){
    echo "Usage: $(dirname $0) src-path s3-bucket"
}

case "$OSTYPE" in
    linux*)
        DATE=$(date -u -d '5 years' "+%a, %d %b %Y %T %Z")
        ;;
    darwin*)
        DATE=$(date -u -v +5y "+%a, %d %b %Y %T %Z")
        ;;
    *)
        echo "don't know how to format dates on this OS"
        exit 1
        ;;
esac

# Check for src dir
if [[ -z "$1" ]]
then
    usage
    echo "src not specified"
    exit 1;
fi
SRC=$1

# Check for dest bucket
if [[ -z "$2" ]]
then
    usage
    echo "s3-bucket not specified"
    exit 1;
fi
S3_BUCKET=$2

# check for AWS client
AWS=$(which aws)
if [[ -z $AWS ]]
then
  echo -e "${RED}AWS cli not installed. "
  exit 1
fi

RED='\e[0;31m'
NOCOLOR='\e[0m'
TMPDIR=$(mktemp -d /tmp/s3-website.XXXXXX)

echo "Creating S3 bucket $S3_BUCKET"
$AWS --region $AWS_REGION s3 mb s3://$S3_BUCKET

# Setup WS bucket
WS_CONFIG=$( cat <<EOF
{
    "IndexDocument": {
        "Suffix":"index.html"
    }
}
EOF
)

set -e

echo "Setting up bucket as a static website"
echo $WS_CONFIG > $TMPDIR/.aws.s3.config
$AWS --region $AWS_REGION s3api put-bucket-website --bucket $S3_BUCKET --website-configuration file:///$TMPDIR/.aws.s3.config
rm $TMPDIR/.aws.s3.config
$AWS --region $AWS_REGION s3api put-bucket-acl --bucket $S3_BUCKET --grant-read 'uri="http://acs.amazonaws.com/groups/global/AllUsers"'

echo "Copying $SRC to $TMPDIR"
cp -a $SRC/* $TMPDIR
# AWS CLI doesn't seem to honor include/exclude with absolute paths so
# change to the temp dir.
pushd $TMPDIR

echo "Gzipping and syncing .js, .css and font files..."
for f in $(find . -name '*.js' -o -name '*.css' -o -name '*.woff' -o -name '*.eot' -o -name '*.ttf' -o -name '*.svg'); do
    gzip -9 -f $f
    mv $f.gz $f
done;

$AWS s3 --region $AWS_REGION sync --acl public-read --exclude '*.*' --include '*.js' --include '*.min' --cache-control="public, max-age=31556900" --expires "$DATE" --content-type "application/javascript" --content-encoding="gzip" . s3://$S3_BUCKET/
$AWS s3 --region $AWS_REGION sync --acl public-read --exclude '*.*' --include '*.css' --include "*.min" --content-type "text/css" --cache-control="public, max-age=31556900" --expires "$DATE"  --content-encoding="gzip" . s3://$S3_BUCKET/
$AWS s3 --region $AWS_REGION sync --acl public-read --exclude '*.*' --include '*.woff' --include "*.eot" --include "*.svg" --include "*.ttf" --cache-control="public, max-age=31556900" --expires "$DATE"  --content-encoding="gzip" . s3://$S3_BUCKET/


echo "Syncing media files..."
$AWS --region $AWS_REGION s3 sync --acl public-read --exclude '*.*' --include '*.gif' --include '*.png' --include '*.jpg' --include '*.ico' --expires "$DATE" --cache-control="public, max-age=31556900"  . s3://$S3_BUCKET/

# Sync html files
echo "Syncing .html"
for f in $(find . -type f -name '*.html'); do
    gzip -9 -f $f
    mv $f.gz $f
done;

$AWS s3 --region $AWS_REGION sync --acl public-read --exclude '*.*' --include  '*.html' --content-encoding "gzip" --cache-control "max-age=7200, must-revalidate" . s3://$S3_BUCKET/

# Sync everything else, but ignore the assets!
echo "Syncing everything else"
$AWS s3 --region $AWS_REGION sync --acl public-read --exclude '.DS_Store' --exclude "*.yml" --exclude 'assets/' --exclude "*.gz" --exclude "*.js" --exclude "*.css" --exclude "*.png" --exclude "*.jpg" --exclude "*.gif" . s3://$S3_BUCKET/

# Sync: remaining files & delete removed
$AWS s3 --region $AWS_REGION sync --acl public-read --delete  . s3://$S3_BUCKET/

# Cleanup
rm -rf $TMPDIR
popd
